{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotRecover"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/ubfoundation\/ubnetworkingtaskrecoveryresult\/cannotrecover"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryResult\/cannotRecover","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cannot recover the failure"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotRecover"}],"title":"UBNetworkingTaskRecoveryResult.cannotRecover","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12UBFoundation30UBNetworkingTaskRecoveryResultO13cannotRecoveryA2CmF","modules":[{"name":"UBFoundation"}]},"hierarchy":{"paths":[["doc:\/\/UBFoundation\/documentation\/UBFoundation","doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryResult"]]},"references":{"doc://UBFoundation/documentation/UBFoundation":{"role":"collection","title":"UBFoundation","abstract":[],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkingTaskRecoveryResult/cannotRecover":{"role":"symbol","title":"UBNetworkingTaskRecoveryResult.cannotRecover","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotRecover"}],"abstract":[{"type":"text","text":"Cannot recover the failure"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryResult\/cannotRecover","kind":"symbol","type":"topic","url":"\/documentation\/ubfoundation\/ubnetworkingtaskrecoveryresult\/cannotrecover"},"doc://UBFoundation/documentation/UBFoundation/UBNetworkingTaskRecoveryResult":{"role":"symbol","title":"UBNetworkingTaskRecoveryResult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UBNetworkingTaskRecoveryResult"}],"abstract":[{"type":"text","text":"The result of attempting a recovery after a network task fails"}],"identifier":"doc:\/\/UBFoundation\/documentation\/UBFoundation\/UBNetworkingTaskRecoveryResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UBNetworkingTaskRecoveryResult"}],"url":"\/documentation\/ubfoundation\/ubnetworkingtaskrecoveryresult"}}}